apiVersion: apps/v1
kind: Deployment
metadata:
   name:  {{ include "config.fullname" . }}
   labels:
      app:  {{ include "config.fullname" . }}
spec:
   replicas: {{ .Values.replicaCount }}
   selector:
      matchLabels:
         app:  {{ include "config.fullname" . }}
   template:
      metadata:
         labels:
            app:  {{ include "config.fullname" . }}
      spec:
         containers:
         -  name:  {{ include "config.fullname" . }}
            image: compucomm/gateway-service:1.2
            imagePullPolicy: Always
            ports:
            -  containerPort: 8111
            env:
            - name: app.profile
              value: dev
            - name: CCOMS_EMP_PORT
              value: "8080"
            - name: CCOMS_DEPT_PORT
              value: "8081"
            - name: CCOMS_ORG_PORT
              value: "8082"
            - name: CCOMS_ZUUL_PORT
              value: "8111"
            readinessProbe:
              httpGet:
                path: /emp/pretty
                port: 8111
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1
            livenessProbe:
              httpGet:
                path: /emp/pretty
                port: 8111
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1