apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{ template "name" . }}
   labels:
      app: {{ template "name" . }}
spec:
   replicas: {{ .Values.replicaCount }}
   selector:
      matchLabels:
         app: {{ template "name" . }}
   template:
      metadata:
         labels:
            app: {{ template "name" . }}
      spec:
         containers:
         -  name: {{ template "name" . }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: Always
            ports:
            -  containerPort: {{ .Values.service.port }}
            env:
            - name: app.profile
              value: dev
            - name: CCOMS_EMP_PORT
              value: "8080"
            - name: CCOMS_DEPT_PORT
              value: "8081"
            - name: CCOMS_ORG_PORT
              value: "8082"
            - name: CCOMS_ZUUL_PORT
              value: "{{ .Values.service.port }}"
            readinessProbe:
              httpGet:
                path: /emp/pretty
                port: {{ .Values.service.port }}
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1
            livenessProbe:
              httpGet:
                path: /emp/pretty
                port: {{ .Values.service.port }}
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1