apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{ template "name" . }}
   labels:
      app: {{ template "name" . }}
spec:
   replicas: {{ .Values.replicaCount }}
   selector:
      matchLabels:
         app: {{ template "name" . }}
   template:
      metadata:
         labels:
            app: {{ template "name" . }}
      spec:
         containers:
         -  name: {{ template "name" . }}
            image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
            imagePullPolicy: Always
            ports:
            -  containerPort: {{ .Values.env.normal.CCOMS_PROXY_PORT }}
            env:
{{- include "helpers.list-env-variables" . | indent 12 }}
            - name: EMP_HOST
              value: "employee.{{ .Release.Namespace }}"
            - name: DEPT_HOST
              value: "department.{{ .Release.Namespace }}"
            - name: ORG_HOST
              value: "organization.{{ .Release.Namespace }}"
            - name: CONFIG_HOST
              value: "config.{{ .Release.Namespace }}"
            - name: CCOMS_ZUUL_PORT
              value: "{{ .Values.env.normal.CCOMS_PROXY_PORT }}"
            readinessProbe:
              httpGet:
                path: /emp/pretty
                port: {{ .Values.env.normal.CCOMS_PROXY_PORT }}
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1
            livenessProbe:
              httpGet:
                path: /emp/pretty
                port: {{ .Values.env.normal.CCOMS_PROXY_PORT }}
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1