apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
spec:
  ports:
    - port: {{ .Values.env.normal.CCOMS_PROXY_PORT }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "name" . }}
  externalIPs:
  -  {{ .Values.externalIPaddress }} 
