apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
spec:
  ports:
    - port: {{ .Values.env.normal.CCOMS_DEPT_PORT }}
      protocol: TCP
  selector:
    app: {{ template "name" . }}
