apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
