apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "name" . }}
  labels:
    role: {{ .Values.mongodb.role }}
    environment: {{ .Values.profile }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "name" . }}
  selector:
    matchLabels:
      role: {{ .Values.mongodb.role }}
      environment: {{ .Values.profile }}
  template:
    metadata:
      labels:
        role: {{ .Values.mongodb.role }}
        environment: {{ .Values.profile }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
        - mongod
        - "--replSet"
        - rs0
        - "--bind_ip"
        - 0.0.0.0
        - "--smallfiles"
        - "--noprealloc"
        volumeMounts:
        - mountPath: "/data/db"
          name: dbvolumes
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.env.normal.CCOMS_DATABASE_PORT }}
        env:
{{- include "helpers.list-env-variables" . | indent 8 }}
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
        - name: MONGO_SIDECAR_POD_LABELS
          value: "role=mongo,environment={{ .Values.profile }}"
  volumeClaimTemplates:
  - metadata:
      name: dbvolumes
    spec:
      storageClassName: manual
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
