{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv0
  labels:
    role: {{ .Values.env.normal.ROLE }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
{{- if (eq "hostPath" .Values.persistence.networkResource) }}
  hostPath:
{{- end }}
{{- if (eq "nfs" .Values.persistence.networkResource) }}
  nfs:
    server: {{ .Values.persistence.server }}
{{- end }}
    path: /u02/pvs/pv0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv1
  labels:
    role: {{ .Values.env.normal.ROLE }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
{{- if (eq "hostPath" .Values.persistence.networkResource) }}
  hostPath:
{{- end }}
{{- if (eq "nfs" .Values.persistence.networkResource) }}
  nfs:
    server: {{ .Values.persistence.server }}
{{- end }}
    path: /u02/pvs/pv1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv2
  labels:
    role: {{ .Values.env.normal.ROLE }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
{{- if (eq "hostPath" .Values.persistence.networkResource) }}
  hostPath:
{{- end }}
{{- if (eq "nfs" .Values.persistence.networkResource) }}
  nfs:
    server: {{ .Values.persistence.server }}
{{- end }}
    path: /u02/pvs/pv2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv3
  labels:
    role: {{ .Values.env.normal.ROLE }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
{{- if (eq "hostPath" .Values.persistence.networkResource) }}
  hostPath:
{{- end }}
{{- if (eq "nfs" .Values.persistence.networkResource) }}
  nfs:
    server: {{ .Values.persistence.server }}
{{- end }}
    path: /u02/pvs/pv3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv4
  labels:
    role: {{ .Values.env.normal.ROLE }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
{{- if (eq "hostPath" .Values.persistence.networkResource) }}
  hostPath:
{{- end }}
{{- if (eq "nfs" .Values.persistence.networkResource) }}
  nfs:
    server: {{ .Values.persistence.server }}
{{- end }}
    path: /u02/pvs/pv4
{{- end }}
