apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
type: Opaque
data:
  database-password: {{ .Values.database.password | b64enc }}
  database-user: {{ .Values.database.user | b64enc }}
  database-name: {{ .Values.database.name | b64enc }}
