apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  database-password: {{ .Values.database-password }}
  database-user: {{ .Values.database-user }}
  database-name: {{ .Values.database-name }}
