apiVersion: v1
kind: Service
metadata:
   name: db
   labels:
      app: mongodb
spec:
   ports:
   -  port: {{ .Values.env.normal.CCOMS_DATABASE_PORT }}
      protocol: TCP
   selector:
      role: {{ .Values.role }}
      environment: {{ .Values.profile }}
   clusterIP: None
