secret:
  name: ccoms-secrets

env:
  secret:
    MONGO_INITDB_ROOT_USERNAME: "admin"
    MONGO_INITDB_ROOT_PASSWORD: "admin123"
    MONGO_INITDB_DATABASE: "admin"
  normal:
    CCOMS_DATABASE_PORT: 27017
    CCOMS_CONFIG_PORT: 8888
    CCOMS_EMP_PORT: 8080
    CCOMS_DEPT_PORT: 8081
    CCOMS_ORG_PORT: 8082
    CCOMS_PROXY_PORT: 8111
    app.profile: dev

profile: dev

## External ip address for Proxy Microservice 
externalIPaddress: 

#####  Mongo Values ##########
role: mongo
## Persistent volume  ##
volume: 
  enabled: true
nfsserverhost: 
