secret:
  name: ccoms-secrets

env:
  secret:
    CCOMS_DATABASE_USERNAME: "admin"
    CCOMS_DATABASE_PASSWORD: "admin123"
    CCOMS_DATABASE_SERVICENAME: "admin"
  normal:
    CCOMS_DATABASE_PORT: 27027
    CCOMS_CONFIG_PORT: 8888
    CCOMS_EMP_PORT: 8080
    CCOMS_DEPT_PORT: 8081
    CCOMS_ORG_PORT: 8082
    CCOMS_PROXY_PORT: 8111
    app:
      profile: dev

## External ip address for Proxy Microservice 
externalIPaddress: 

#####  Mongo Values ##########
role: mongo
## Persistent volume  ##
volume: 
  enabled: true
nfsserverhost: 
