secret:
  name: ccoms-secrets

env:
  secrets:
    DB_USER: "mongo"
    DB_PASSWD: "mongo123"
    DATABASE: "ccoms"
  normal:
    CCOMS_DATABASE_PORT: 27017
    CCOMS_CONFIG_PORT: 8888
    CCOMS_EMP_PORT: 8080
    CCOMS_DEPT_PORT: 8081
    CCOMS_ORG_PORT: 8082
    CCOMS_PROXY_PORT: 8111
    app.profile: dev

profile: dev

## External ip address for Proxy Microservice 
externalIPaddress: 

#####  Mongo Values ##########
mongodb:
  enabled: true

## Persist data to a persistent volume
persistence:
  enabled: true
  storageClass: manual
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  size: 400Mi
  pvs: 5
  mountPath: /data/db
  ### TGoogle Compute Engine persistent disk, an NFS share, or an Amazon Elastic Block Store volume
  ### hostpath is for local and nfs is for nfs 
  ## network 
  networkResource: 
    hostPath:
  ## provide below value in case you are using nfs network resource, otherwise below value will not be used
  server: 
  # annotations: {}
  # subPath: ""
  # existingClaim:


