apiVersion: apps/v1
kind: Deployment
metadata:
   name:  {{ include "config.fullname" . }}
   labels:
      app:  {{ include "config.fullname" . }}
spec:
   replicas: {{ .Values.replicaCount }}
   selector:
      matchLabels:
         app:  {{ include "config.fullname" . }}
   template:
      metadata:
         labels:
            app:  {{ include "config.fullname" . }}
      spec:
         containers:
         -  name:  {{ include "config.fullname" . }}
            image: compucomm/org-service:1.2
            imagePullPolicy: Always
            ports:
            -  containerPort: 8082
            env:
            - name: app.profile
              value: dev
            - name: CCOMS_DATABASE_USERNAME
              value: admin
            - name: CCOMS_DATABASE_PASSWORD
              value: admin123
            - name: CCOMS_DATABASE_SERVICENAME
              value: admin
            - name: CCOMS_DATABASE_PORT
              value: "27017"
            - name: CCOMS_EMP_PORT
              value: "8080"
            - name: CCOMS_DEPT_PORT
              value: "8081"
            - name: CCOMS_ORG_PORT
              value: "8082"
            readinessProbe:
               httpGet:
                  path: /pretty
                  port: 8082
               initialDelaySeconds: 120
               periodSeconds: 10
               successThreshold: 1
            livenessProbe:
               httpGet:
                  path: /pretty
                  port: 8082
               initialDelaySeconds: 120
               periodSeconds: 10
               successThreshold: 1