apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{ template "name" . }}
   labels:
      app: {{ template "name" . }}
spec:
   replicas: {{ .Values.replicaCount }}
   selector:
      matchLabels:
         app: {{ template "name" . }}
   template:
      metadata:
         labels:
            app: {{ template "name" . }}
      spec:
         containers:
         -  name: {{ template "name" . }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
            -  containerPort: {{ .Values.env.normal.CCOMS_ORG_PORT }}
            env:
{{- include "helpers.list-env-variables" . | indent 12 }}
            - name: EMP_HOST
              value: "employee.{{ .Release.Namespace }}"
            - name: DEPT_HOST
              value: "department.{{ .Release.Namespace }}"
            - name: ORG_HOST
              value: "{{ template "name" . }}.{{ .Release.Namespace }}"
            - name: MONGO_HOST
              value: "mongo.{{ .Release.Namespace }}"
            - name: CONFIG_HOST
              value: "config.{{ .Release.Namespace }}"
            readinessProbe:
               httpGet:
                  path: /pretty
                  port: {{ .Values.env.normal.CCOMS_ORG_PORT }}
               initialDelaySeconds: 120
               periodSeconds: 10
               successThreshold: 1
            livenessProbe:
               httpGet:
                  path: /pretty
                  port: {{ .Values.env.normal.CCOMS_ORG_PORT }}
               initialDelaySeconds: 120
               periodSeconds: 10
               successThreshold: 1