apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.env.normal.CCOMS_ORG_PORT }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "name" . }}
  externalIPs:
   -  {{ .Values.externalIPaddress }} 
