replicaCount: 1

image:
  repository: compucomm/dept-service
  tag: 1.3
  pullPolicy: IfNotPresent
  ports:
    containerPort: 8888
env:
  app.profile: dev

service:
  type:
  port: 8888

ingress:
  enabled: false
