apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfg-ms
  namespace: ccoms
  labels:
    app: cfg-ms
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: cfg-ms
  template:
    metadata:
      labels:
        app: cfg-ms
    spec:
      containers:
      - name: cfg-ms
        image: 'compucomm/config-service'
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        env:
        - name: app.profile
          value: dev
