apiVersion: v1
kind: Service
metadata:
  name:{{ template "name" . }}
  labels:
{{ include "config.fullname" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "name" . }}
