replicaCount: 5

image:
  repository: mongo
  tag: 4.0
  pullPolicy: Always

ingress:
  enabled: false

db_secret:
  name: db-secrets
  
env:
  db_secrets:
    MONGO_INITDB_ROOT_USERNAME: "admin"
    MONGO_INITDB_ROOT_PASSWORD: "admin123"
    MONGO_INITDB_DATABASE: "admin"
  normal:
    DATABASE_PORT: 27017
    ROLE: mongo

