replicaCount: 1

image:
  repository: mongo
  tag: 3.4
  pullPolicy: Always
  ports:
    containerPort: 8888
env:
  app.profile: dev

role: mongo

service:
  type:
  port: 8888

ingress:
  enabled: false

database:
  service_name: 
  password:
  user: 
  name: