replicaCount: 1

image:
  repository: mongo
  tag: 3.4
  pullPolicy: Always

profile: dev

role: mongo

service:
  port: 27027

ingress:
  enabled: false

database:
  service_name: admin
  password: admin123
  user: admin

## Persisten volume related parameters
nfsserverhost: 

